// מיפוי אוטומטי בין שם פרוצדורה לסוג טופס GynStones CBD
// מקור: EPA_FormType_Mapping.xlsx

export const EPA_FORM_TYPE_MAP = {
  // OB
  "יולדות-ביקורים עם מתמחה": "clinical_management",
  "יולדות-ביקור לבד- להציג את הביקור": "clinical_management",
  "ביקור יולדות- אינטראקציה עם 2 מטופלות": "clinical_management",
  "ביקור יולדות- הצגה לרופא בכיר": "clinical_management",
  "יולדות-לעבור על10 מכתבי שחרור": "ward_management",
  "יולדות-לעבור על10 מכתבי שחרור (5 פסיולוגי 5 קיסרי)": "ward_management",
  "יולדות - מכתב שחרור קרע מתקדם": "ward_management",
  "יולדות - מכתב שחרור מורכב": "ward_management",
  "מכתבי שחרור": "ward_management",
  "קבלה לקיסרי": "clinical_management",
  "קבלה לקיסרי - צפיה": "clinical_management",
  "קבלה לקיסרי - יום קבלות": "clinical_management",
  "קיסרי- הכרת המטופלת, השכבה, רחצה": "procedural",
  "קיסרי- הכרת המטופלת השכבה רחצה": "procedural",
  "הכנסת קטטר": "procedural",
  "כתיבת דו\"ח ניתוח": "clinical_management",
  "כתיבת דוח ניתוח": "clinical_management",
  "ניהול ראשוני של מצבי חירום לאחר לידה": "clinical_management",
  "טיפול ביולדת -טיפול בחום אחרי לידה וכו'": "clinical_management",
  "טיפול ביולדת -טיפול בחום אחרי לידה וכו": "clinical_management",
  "PV - אחרי מיילדת או רופא": "procedural",
  "PV": "procedural",
  "הכנסת בלון": "procedural",
  "תפירה בחדר לידה": "procedural",
  "פענוח מוניטור": "clinical_management",
  "פענוח של מוניטור": "clinical_management",
  "BPP": "procedural",
  "קבלה במיון יולדות- אנמנזה, אינטראקציה, כיתוב": "clinical_management",
  "קבלה במיון יולדות- אנמנזה אינטראקציה": "clinical_management",
  "קבלה בחדר לידה/ ביקור בחדר לידה": "clinical_management",
  "ליווי יולדת בחדר לידה, כולל קבלת לידה (לפחות 5 לידות ראשונות)": "clinical_management",
  "ליווי יולדת בחדר לידה": "clinical_management",
  "ייעוץ לTOLAC כולל הבנה של התווית נגד": "clinical_management",
  "ניהול TOLAC": "clinical_management",
  "אם ועובר-ניהול יום במחלקה": "ward_management",
  "אם ועובר-העברת מקל בישיבת העברה": "ward_management",
  "ניהול מעקב הריון רגיל": "clinical_management",
  "ניתוח קיסרי כעוזר": "procedural",
  "ניתוח קיסרי כמנתח ראשון": "procedural",
  "ניהול השראת לידה": "clinical_management",
  "השראת לידה": "clinical_management",
  "ניהול לידה ראשונה": "clinical_management",
  "קבלת לידה רגילה": "procedural",
  "אפיזיוטומיה - ביצוע": "procedural",
  "אפיזיוטומיה": "procedural",
  "ניהול שלב 3": "procedural",
  "טיפול ביולדת -טיפול במקרה חירום מורכב אחרי לידה": "clinical_management",
  "ניהול מקרה במיון המיילדותי": "clinical_management",
  "שליטה וניהול עמדת המיון המיילדותי": "ward_management",
  "ניהול מקרה של הריון בסיכון גבוה (אשפוז יום)": "clinical_management",
  "ניהול מקרה של הריון בסיכון גבוה": "clinical_management",
  "ניהול מקרה חירום מיילדותי": "clinical_management",
  "ניהול לידה מורכבת": "clinical_management",
  "ניהול PPH בחדר לידה": "clinical_management",
  "Revision": "procedural",
  "Manual lysis": "procedural",
  "ניהול לידת תאומים": "clinical_management",
  "לידת VACUUM": "procedural",
  "תפירה מורכבת כולל אבחנה של OASIS": "procedural",
  "ביצוע קיסרי מורכב": "procedural",
  "ניהול מקרה מורכב במשכב לידה": "clinical_management",
  "ניהול חדר לידה ותורנות": "ward_management",

  // GYN
  "קבלה במיון נשים": "clinical_management",
  "קבלה במרפאת נשים/ מיון": "clinical_management",
  "קבלה בטרום ניתוח": "clinical_management",
  "הכנסת מטופלת לחדר ניתוח, כולל השכבה, SIGN IN, הכנת ציוד ורחצה": "procedural",
  "הכנה לניתוח- התנהגות בחדר ניתוח": "procedural",
  "הבנה של שלבי הניתוח פשוט": "procedural",
  "הבנה של שלבי הניתוח": "procedural",
  "תפירה וקשירה": "procedural",
  "קשירה": "procedural",
  "ניהול יום במחלקה (כולל כל שלבי היום)": "ward_management",
  "ניהול יום במחלקה": "ward_management",
  "ניהול ביקור בוקר (הכרת נשים, הצגה, תוכנית, רישום)": "ward_management",
  "מענה ראשוני למצב חירום": "ward_management",
  "העברת מקל בישיבת העברה": "ward_management",
  "ניהול מקרה במיון הגינקולוגי (ניהול מלא כולל מעבר לחדר ניתוח במידת הצורך)": "clinical_management",
  "ניהול מקרה במיון הגינקולוגי": "clinical_management",
  "טיפול במטופלת עם סיבוכי הריון צעיר (הפלה מאיימת, אקטופי מסוגים שונים)": "clinical_management",
  "טיפול במטופלת עם סיבוכי הריון צעיר": "clinical_management",
  "טיפול למטופלת במרפאת נשים": "clinical_management",
  "בדיקת PAP/HPV": "procedural",
  "פיפל": "procedural",
  "הוצאת IUD": "procedural",
  "הידרוסונוגרפיה": "procedural",
  "צילום רחם": "procedural",
  "הפסקת הריון": "procedural",
  "ייעוץ על מניעת הריון": "clinical_management",
  "טיפול בהפלה נדחית": "procedural",
  "הכנסת IUD": "procedural",
  "ניתוחים קטנים (גרידות, ברתולין)": "procedural",
  "ניתוחים קטנים": "procedural",
  "עזרה בלפרוסקופיה והיסטרוסקופיה": "procedural",
  "ניהול מקרה גינקולוגי אמבולטורי מורכב": "clinical_management",
  "מקרה ילדות ומתבגרות": "clinical_management",
  "קוניזציה": "procedural",
  "ייעוץ לנשים עם תלונות של רצפת האגן": "clinical_management",
  "הערכה לנשים עם אנדומטרוזיס": "clinical_management",
  "היסטרוסקופיה ניתוחית": "procedural",
  "כריתת רחם": "procedural",
  "ניתוחי של רצפת האגן כולל TVH": "procedural",
  "ניתוח פתוח": "procedural",
  "טיפול של סיבוכים של ניתוחים": "clinical_management",

  // IVF
  "הערכה של מטופלת/זוג עם אי פוריות כולל תוכנית טיפול": "clinical_management",
  "כתיבת הנחיות לפרופיל הורמונלי ופענוח תשובה": "clinical_management",
  "הנחיות בדיקת זרע ופענוח בדיקת זרע": "clinical_management",
  "הערכה של מדדי רזרבה שחלתית": "clinical_management",
  "ביצוע בדיקת US למטופלת פריון: AFC, שחלות, הערכת רחם": "procedural",
  "הערכה של מטופלת עם הפלות חוזרות/RPF": "clinical_management",
  "הערכה של מטופלת לשימור פוריות": "clinical_management",
  "הערכת מטופל/ת ל PGT": "clinical_management",
  "ניהול מטופלת בתהליך של IVF": "clinical_management",
  "בירור אי פוריות גבר": "clinical_management",
  "IUI": "procedural",
  "השראת ביוץ": "clinical_management",
  "ניהול סיבוכים של ART": "clinical_management",

  // ONCO
  "מקרה אמבולטורי של ממאירות גינקולוגית": "clinical_management",
  "חדר ניתוח": "procedural",
  "אשפוז יום": "clinical_management",
  "מחלקה": "clinical_management",
  "קולפוסקופיה": "procedural",

  // כללי / US
  "אורך צוואר": "procedural",
  "הערכת משקל": "procedural",
  "דופלר של חבל הטבור": "procedural",
  "הריון צעיר": "procedural",
  "פתולוגיה בטפולות": "procedural",
  "מסירת בשורות רעות -תקשורת מתקדמת על בשורות רעות": "communication",
  "מחקר, הבנת הספרות": "teaching_research",
  "מחקר הבנת הספרות": "teaching_research",
  "הוראה": "teaching_research",
  "ניהול תורנות כתורן ראשון": "ward_management",
  "ניהול תורנות כתרון על": "ward_management",
  "מחקר ופרסום": "teaching_research",
};

export function getFormTypeForProcedure(procedureName) {
  if (!procedureName) return null;
  return EPA_FORM_TYPE_MAP[procedureName] || null;
}